server:
  port: 7091

spring:
  application:
    name: seata-server

logging:
  config: classpath:logback-spring.xml
  file:
    path: ${user.home}/logs/seata
  extend:
    kafka-appender:
      # off by default
      enabled: true
      bootstrap-servers: kafka-server:9092
      topic: log_seata
      producer:
        acks: 0
        linger-ms: 1000
        max-block-ms: 0
    metric-appender:
      # off by default
      enabled: true

seata:
  # 看日志，还有 lock 存储，这个改怎么配置？存哪里？
  config:
    # support: nacos, consul, apollo, zk, etcd3
    type: nacos
    nacos:
      server-addr: nacos:8848
      namespace: seata-server
      group: SEATA_GROUP
      username: seata
      password: seata
      # 默认是：seata.properties
      data-id: seataServer.properties
  registry:
    # support: nacos 、 eureka 、 redis 、 zk  、 consul 、 etcd3 、 sofa 、 seata
    type: seata
    metadata:
      weight: 100
    seata:
      server-addr: seata-naming-server:8081
      cluster: default
      namespace: public
      heartbeat-period: 5000
      metadata-max-age-ms: 30000
      username: seata
      password: seata
#    type: nacos
#    nacos:
#      application: seata-server
#      server-addr: nacos:8848
#      group: SEATA_GROUP
#      namespace: seata-server
#      # tc集群名称
#      cluster: default
#      username: seata
#      password: seata
#  # 在 NACOS 配置
#  store:
#    # support: file 、 db 、 redis 、 raft
#    mode: db
#    session:
#      mode: db
#    lock:
#      mode: db
#    db:
#      datasource: hikari
#      db-type: mysql
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      url: jdbc:mysql://mysql-seata:3306/db_seata?useUnicode=true&characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
#      user: admin_seata
#      password: 123456
#      min-conn: 1
#      max-conn: 10
#      global-table: global_table
#      branch-table: branch_table
#      lock-table: lock_table
#      distributed-lock-table: distributed_lock
#      vgroup-table: vgroup_table
#      query-limit: 1000
#      max-wait: 5000
#      hikari:
#        idle-timeout: 600000
#        keepalive-time: 120000
#        max-lifetime: 1800000
#        validation-timeout: 5000
  # TODO 访问 http://127.0.0.1:9898/metrics 看不到监控数据
  metrics:
    enabled: true
    registry-type: compact
    exporter-list: prometheus
    exporter-prometheus-port: 9898
