server:
  port: 7091

spring:
  application:
    name: seata-server

logging:
  config: classpath:logback-spring.xml
  file:
    path: ${user.home}/logs/seata
  extend:
    # TODO Kafka 没有日志
    kafka-appender:
      # off by default
      enabled: true
      bootstrap-servers: kafka-server:9092
      topic: log_seata
      producer:
        acks: 0
        linger-ms: 1000
        max-block-ms: 0
    metric-appender:
      # off by default
      enabled: true

seata:
  # 看日志，还有 lock 存储，这个改怎么配置？存哪里？
  config:
    # support: nacos, consul, apollo, zk, etcd3
#    type: file
    type: nacos
    nacos:
      server-addr: nacos:8848
      namespace: seata-server
      group: SEATA_GROUP
      username: seata
      password: seata
#      data-id: seataServer.properties
  registry:
    # support: nacos 、 eureka 、 redis 、 zk  、 consul 、 etcd3 、 sofa 、 seata
    type: seata
    metadata:
      weight: 100
    seata:
      server-addr: seata-naming-server:8081
      cluster: default
      namespace: public
      heartbeat-period: 5000
      metadata-max-age-ms: 30000
      username: seata
      password: seata
#    type: nacos
#    nacos:
#      application: seata-server
#      server-addr: nacos:8848
#      group: SEATA_GROUP
#      namespace: seata-server
#      # tc集群名称
#      cluster: default
#      username: seata
#      password: seata
#  # 在 NACOS 配置
#  store:
#    # support: file 、 db 、 redis
##    mode: file
#    mode: db
#    db:
#      datasource: druid
#      dbType: mysql
#      # 需要根据mysql的版本调整driverClassName
#      # mysql8及以上版本对应的driver：com.mysql.cj.jdbc.Driver
#      # mysql8以下版本的driver：com.mysql.jdbc.Driver
#      driverClassName: com.mysql.cj.jdbc.Driver
#      # 连接 MySQL 8.4 需要加 allowPublicKeyRetrieval=true 参数
#      url: jdbc:mysql://mysql-seata:3306/db_seata?useUnicode=true&characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
#      user: admin_seata
#      password: 123456
  # TODO 访问 http://127.0.0.1:9898/metrics 看不到监控数据
  metrics:
    enabled: true
    registry-type: compact
    exporter-list: prometheus
    exporter-prometheus-port: 9898

#  server:
#    service-port: 8091 #If not configured, the default is '${server.port} + 1000'
  security:
    secretKey: SeataSecretKey0c382ef121d778043159209298fd40bf3850a017
    tokenValidityInMilliseconds: 1800000
    ignore:
      urls: /,/**/*.css,/**/*.js,/**/*.html,/**/*.map,/**/*.svg,/**/*.png,/**/*.ico,/console-fe/public/**,/api/v1/auth/login
